"""empty message

Revision ID: aa79f3006055
Revises: a33b3875b405
Create Date: 2022-07-01 11:24:48.855798

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'aa79f3006055'
down_revision = 'a33b3875b405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('estimate', sa.String(length=20), nullable=True))
    op.drop_column('topics', 'time_estimate')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('topics', sa.Column('time_estimate', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.drop_column('topics', 'estimate')
    # ### end Alembic commands ###
